name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf
      - name: Commit and push PDE file
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config --local user.email "yzz0225@auburn.edu"
          git config --local user.name "Yimin Zhong"
          git add main.pdf
          git commit -m "Upload PDF file" || echo "No changes to commit"
          git push